name: Danger

on: 
  pull_request:
    types:
      [opened, synchronize, reopened, edited]

jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
            node-version: 10.x

      - name: Install dependencies
        run: |
            npm install -g yarn
            yarn add danger --dev

      - name: Danger
        run: yarn danger ci --dangerfile .github/dangerfile.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}

